server:
  port: 8761


spring:
  config:
    activate:
      on-profile: dev
  application:
    name: discovery service-dev

logging:
  level:
    root: DEBUG


# 유레카가 자기 자신을 등록하지 않아도됌
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



