server:
  port: 8761


spring:
  config:
    activate:
      on-profile: prod
  application:
    name: discovery service-prod

logging:
  level:
    root: INFO


# 유레카가 자기 자신을 등록하지 않아도됌
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



