server:
  port: 10149

spring:
  application:
    name: eureka

logging:
  level:
    root: ERROR


# 유레카가 자기 자신을 등록하지 않아도됌
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



