name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Delete files in server
        run: rm -rf /home/be8/be8-team4/eureka/*

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_NHN_IP }}
          username: ${{ secrets.SSH_NHN_ID }}
          port: ${{ secrets.SSH_NHN_PORT }}
          password: ${{ secrets.SSH_NHN_PASSWORD }}
          source: "target/*.jar"
          target: "/home/be8/be8-team4/eureka"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_NHN_IP }}
          username: ${{ secrets.SSH_NHN_ID }}
          port: ${{ secrets.SSH_NHN_PORT }}
          password: ${{ secrets.SSH_NHN_PASSWORD }}
          script: |
            echo -e "Starting jar on port 10149"
            nohup /usr/local/java/java21/bin/java -Dserver.port=10149 -Dspring.profiles.active=nhn -jar /home/be8/be8-team4/shop/target/BookStoreEureka-0.0.1-SNAPSHOT.jar > /home/be8/be8-team4/eureka/log_10149.log 2>&1 &


